default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: ollida_development

test:
  <<: *default
  database: ollida_test

production:
  <<: *default
  database: ollida_production
  username: ollida
  password: <%= ENV['ollida_production_password'] %>